name: dev-story
description: "태스크/서브태스크를 구현하고 테스트를 작성하며 검증하고 수락 기준에 따라 스토리 파일을 업데이트하여 스토리를 실행합니다"
author: "BMad"

# Critical variables from config
config_source: "{project-root}/{bmad_folder}/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
user_skill_level: "{config_source}:user_skill_level"
document_output_language: "{config_source}:document_output_language"
story_dir: "{config_source}:sprint_artifacts"
date: system-generated

story_file: "" # Explicit story path; auto-discovered if empty
# Context file uses same story_key as story file (e.g., "1-2-user-authentication.context.xml")
context_file: "{story_dir}/{{story_key}}.context.xml"

# Workflow components
installed_path: "{project-root}/{bmad_folder}/bmm/workflows/4-implementation/dev-story"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

standalone: true

web_bundle: false
