# 프로젝트 브레인스토밍 워크플로우 설정
name: "brainstorm-project"
description: "프로젝트별 맥락과 가이드를 제공하여 CIS 브레인스토밍 워크플로우를 조율하고 프로젝트 브레인스토밍 세션을 촉진합니다."
author: "BMad"

# Critical variables from config
config_source: "{project-root}/{bmad_folder}/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
document_output_language: "{config_source}:document_output_language"
user_skill_level: "{config_source}:user_skill_level"
date: system-generated

# Module path and component files
installed_path: "{project-root}/{bmad_folder}/bmm/workflows/1-analysis/brainstorm-project"
template: false
instructions: "{installed_path}/instructions.md"

# Context document for project brainstorming
project_context: "{installed_path}/project-context.md"

# CORE brainstorming workflow to invoke
core_brainstorming: "{project-root}/{bmad_folder}/core/workflows/brainstorming/workflow.yaml"

standalone: true

web_bundle:
  name: "brainstorm-project"
  description: "프로젝트별 맥락과 가이드를 제공하여 CIS 브레인스토밍 워크플로우를 조율하고 프로젝트 브레인스토밍 세션을 촉진합니다."
  author: "BMad"
  instructions: "{bmad_folder}/bmm/workflows/1-analysis/brainstorm-project/instructions.md"
  template: false
  web_bundle_files:
    - "{bmad_folder}/bmm/workflows/1-analysis/brainstorm-project/instructions.md"
    - "{bmad_folder}/bmm/workflows/1-analysis/brainstorm-project/project-context.md"
    - "{bmad_folder}/core/workflows/brainstorming/workflow.yaml"
  existing_workflows:
    - core_brainstorming: "{bmad_folder}/core/workflows/brainstorming/workflow.yaml"
