# Review Story Workflow
name: code-review
description: "검토 준비 완료로 표시된 완료된 스토리에 대해 시니어 개발자 코드 검토 수행. story-context, epic tech-spec, repo docs, 최신 모범 사례를 위한 MCP 서버 활용 및 웹 검색을 대체 수단으로 사용. 구조화된 검토 노트를 스토리에 추가."
author: "BMad"

# Critical variables from config
config_source: "{project-root}/{bmad_folder}/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
user_skill_level: "{config_source}:user_skill_level"
document_output_language: "{config_source}:document_output_language"
date: system-generated
sprint_artifacts: "{config_source}:sprint_artifacts"
sprint_status: "{sprint_artifacts}/sprint-status.yaml || {output_folder}/sprint-status.yaml"

# Workflow components
installed_path: "{project-root}/{bmad_folder}/bmm/workflows/4-implementation/code-review"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"
template: false

variables:
  story_dir: "{sprint_artifacts}"
  tech_spec_search_dir: "{output_folder}"
  tech_spec_glob_template: "tech-spec-epic-{{epic_num}}*.md"
  arch_docs_search_dirs: |
    - "{output_folder}"
  arch_docs_file_names: |
    - architecture.md
  backlog_file: "{output_folder}/backlog.md"
  update_epic_followups: true
  epic_followups_section_title: "Post-Review Follow-ups"

# Smart input file references - handles both whole docs and sharded docs
# Priority: Whole document first, then sharded version
# Strategy: SELECTIVE LOAD - only load the specific epic needed for this story review
input_file_patterns:
  architecture:
    whole: "{output_folder}/*architecture*.md"
    sharded: "{output_folder}/*architecture*/index.md"
  ux_design:
    whole: "{output_folder}/*ux*.md"
    sharded: "{output_folder}/*ux*/index.md"
  epics:
    whole: "{output_folder}/*epic*.md"
    sharded_index: "{output_folder}/*epic*/index.md"
    sharded_single: "{output_folder}/*epic*/epic-{{epic_num}}.md"
  document_project:
    sharded: "{output_folder}/docs/index.md"

standalone: true
web_bundle: false
