# Story Ready Workflow (SM Agent)
name: story-ready
description: "작성된 스토리를 개발 준비 상태로 표시하고 상태 파일에서 TODO → IN PROGRESS로 이동합니다. 검색이 필요 없는 간단한 상태 업데이트 워크플로우입니다."
author: "BMad"

# Critical variables from config
config_source: "{project-root}/{bmad_folder}/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated
sprint_status: "{output_folder}/sprint-status.yaml || {sprint_artifacts}/sprint-status.yaml"

# Workflow components
installed_path: "{project-root}/{bmad_folder}/bmm/workflows/4-implementation/story-ready"
instructions: "{installed_path}/instructions.md"

# Variables and inputs
variables:
  story_dir: "{config_source}:sprint_artifacts"

standalone: true

web_bundle: false
