# Story Done Workflow (DEV Agent)
name: story-done
description: "스토리를 완료로 표시 (DoD 완료)하고 상태 파일에서 현재 상태 → DONE으로 이동. 스토리 큐를 진행. 검색이 필요 없는 간단한 상태 업데이트 워크플로우."
author: "BMad"

# Critical variables from config
config_source: "{project-root}/{bmad_folder}/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated
sprint_status: "{context_dir}/sprint-status.yaml || {output_folder}/sprint-status.yaml"

# Workflow components
installed_path: "{project-root}/{bmad_folder}/bmm/workflows/4-implementation/story-done"
instructions: "{installed_path}/instructions.md"

# Variables and inputs
variables:
  story_dir: "{config_source}:sprint_artifacts/stories" # Directory where stories are stored

# Output configuration - no output file, just status updates
default_output_file: ""

standalone: true

web_bundle: false
