name: sprint-planning
description: "4단계 구현을 위한 스프린트 상태 추적 파일을 생성하고 관리하며, 에픽 파일에서 모든 에픽과 스토리를 추출하여 개발 생명주기 전체에 걸쳐 상태를 추적합니다"
author: "BMad"

# Critical variables from config
config_source: "{project-root}/{bmad_folder}/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated
sprint_artifacts: "{config_source}:sprint_artifacts"

# Workflow components
installed_path: "{project-root}/{bmad_folder}/bmm/workflows/4-implementation/sprint-planning"
instructions: "{installed_path}/instructions.md"
template: "{installed_path}/sprint-status-template.yaml"
validation: "{installed_path}/checklist.md"

# Variables and inputs
variables:
  # Project identification
  project_name: "{config_source}:project_name"

  # Tracking system configuration
  tracking_system: "file-system" # Options: file-system, Future will support other options from config of mcp such as jira, linear, trello
  story_location: "{project-root}/docs/stories" # Relative path for file-system, Future will support URL for Jira/Linear/Trello
  story_location_absolute: "{config_source}:sprint_artifacts" # Absolute path for file operations

  # Source files (file-system only)
  epics_location: "{output_folder}" # Directory containing epic*.md files
  epics_pattern: "epic*.md" # Pattern to find epic files

  # Output configuration
  status_file: "{sprint_artifacts}/sprint-status.yaml"

# Smart input file references - handles both whole docs and sharded docs
# Priority: Whole document first, then sharded version
# Strategy: FULL LOAD - sprint planning needs ALL epics to build complete status
input_file_patterns:
  epics:
    whole: "{output_folder}/*epic*.md"
    sharded: "{output_folder}/*epic*/index.md"

# Output configuration
default_output_file: "{status_file}"

standalone: true

web_bundle: false
