# Test Architect workflow: test-design
name: testarch-test-design
description: "이중 모드 워크플로우: (1) 솔루션 단계의 시스템 수준 테스트 가능성 검토, 또는 (2) 구현 단계의 에픽 수준 테스트 계획. 프로젝트 단계에 따라 모드 자동 감지."
author: "BMad"

# Critical variables from config
config_source: "{project-root}/{bmad_folder}/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
document_output_language: "{config_source}:document_output_language"
date: system-generated

# Workflow components
installed_path: "{project-root}/{bmad_folder}/bmm/workflows/testarch/test-design"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"
template: "{installed_path}/test-design-template.md"

# Variables and inputs
variables:
  design_level: "full" # full, targeted, minimal - scope of design effort
  mode: "auto-detect" # auto-detect (default), system-level, epic-level

# Output configuration
# Note: Actual output file determined dynamically based on mode detection
# - System-Level (Phase 3): {output_folder}/test-design-system.md
# - Epic-Level (Phase 4): {output_folder}/test-design-epic-{epic_num}.md
default_output_file: "{output_folder}/test-design-epic-{epic_num}.md"

# Required tools
required_tools:
  - read_file # Read PRD, epics, stories, architecture docs
  - write_file # Create test design document
  - list_files # Find related documentation
  - search_repo # Search for existing tests and patterns

# Recommended inputs
recommended_inputs:
  - prd: "Product Requirements Document for context"
  - epics: "Epic documentation (epics.md or specific epic)"
  - story: "Story markdown with acceptance criteria"
  - architecture: "Architecture documents (architecture.md, tech-spec)"
  - existing_tests: "Current test coverage for gap analysis"

tags:
  - qa
  - planning
  - test-architect
  - risk-assessment
  - coverage

execution_hints:
  interactive: false # Minimize prompts
  autonomous: true # Proceed without user input unless blocked
  iterative: true

web_bundle: false
