# 구현 준비 확인 - 워크플로우 구성
name: solutioning-gate-check
description: "4단계 구현으로 전환하기 전에 모든 기획 및 솔루션 작업 단계가 완료되고 올바르게 정렬되었는지 체계적으로 검증합니다. PRD, 아키텍처 및 스토리가 격차나 모순 없이 일관성을 갖추도록 보장합니다."
author: "BMad Builder"

# Critical variables from config
config_source: "{project-root}/{bmad_folder}/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
document_output_language: "{config_source}:document_output_language"
date: system-generated

# Workflow status integration
workflow_status_workflow: "{project-root}/{bmad_folder}/bmm/workflows/workflow-status/workflow.yaml"
workflow_paths_dir: "{project-root}/{bmad_folder}/bmm/workflows/workflow-status/paths"
workflow_status_file: "{output_folder}/bmm-workflow-status.yaml"

# Module path and component files
installed_path: "{project-root}/{bmad_folder}/bmm/workflows/3-solutioning/solutioning-gate-check"
template: "{installed_path}/template.md"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Output configuration
default_output_file: "{output_folder}/implementation-readiness-report-{{date}}.md"

# Input requirements
recommended_inputs:
  - prd: "Product Requirements Document with FRs and NFRs"
  - architecture: "System Architecture with decisions and patterns"
  - tech_spec: "Technical Specification (for Quick Flow track)"
  - epics: "Epic breakdown with user stories"
  - ux_design: "UX design specification (if UI components)"

# Smart input file references - handles both whole docs and sharded docs
# Priority: Whole document first, then sharded version
input_file_patterns:
  prd:
    whole: "{output_folder}/*prd*.md"
    sharded: "{output_folder}/*prd*/index.md"
  epics:
    whole: "{output_folder}/*epic*.md"
    sharded: "{output_folder}/*epic*/index.md"
  architecture:
    whole: "{output_folder}/*architecture*.md"
    sharded: "{output_folder}/*architecture*/index.md"
  ux_design:
    whole: "{output_folder}/*ux*.md"
    sharded: "{output_folder}/*ux*/index.md"
  tech_spec:
    whole: "{output_folder}/*tech-spec*.md"
    sharded: "{output_folder}/*tech-spec*/index.md"
  document_project:
    sharded: "{output_folder}/docs/index.md"

standalone: true

web_bundle: false
